version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: plantservice
      POSTGRES_USER: plantservice
      POSTGRES_PASSWORD: plantservice
  web:
    build: .
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      DATABASE_URL: postgres://plantservice:plantservice@db:5432/plantservice
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--shared-socket", "[::]:80", "--http", "=0", "--protocol", "uwsgi", "--wsgi", "plantservice:app", "--master", "--enable-threads" ] 