version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: plantservice
      POSTGRES_USER: plantservice
      POSTGRES_PASSWORD: plantservice
  web:
    build: .
    depends_on:
      - db
    ports:
      - '80:80'
    environment:
      DATABASE_URL: postgres://plantservice:plantservice@db:5432/plantservice
